# Build helper for MulVie.
# The rustup GNU toolchain ships dlltool.exe / gcc in its `self-contained`
# folder but doesn't put it on PATH, so builds that touch the Windows API
# crates fail with "dlltool.exe: program not found". This adds it back.
#
# Usage:
#   .\build.ps1                 # debug build
#   .\build.ps1 --release       # optimized, self-contained exe for the USB stick
#   .\build.ps1 run             # cargo run (debug)

$ErrorActionPreference = 'Stop'
# Full MinGW-w64 (dlltool + as + gcc) is required because modern crates use
# raw-dylib, whose GNU-target import libraries are generated by dlltool.
# Adjust to wherever your MinGW-w64 lives.
$mingw = 'C:\Tools\mingw\mingw64\bin'
$env:PATH = "$env:USERPROFILE\.cargo\bin;$mingw;$env:PATH"

# Strip machine-specific absolute paths from the binary (rustc bakes
# panic-location source paths in — the user profile via the cargo registry,
# the repo dir via build OUT_DIRs). Privacy: nothing identifying may ship.
$env:RUSTFLAGS = ("$env:RUSTFLAGS " +
    "--remap-path-prefix=$env:USERPROFILE=~ " +
    "--remap-path-prefix=$PSScriptRoot=~mulvie").Trim()

if ($args.Count -ge 1 -and $args[0] -eq 'run') {
    cargo run @($args[1..($args.Count-1)])
} else {
    cargo build @args
}
